### ISSUE TITLE
CWManage 

### ISSUE THREAD

**Issue by BrianNowak** [KelvinTegelaar/PowerShellWarrantyReports#5]
Line 21 of Get-WarrantyCWM.ps1 has a typo in the variable for the CWM API URL.  It does not match the defined variable and reports:  invoke-restmethod : Invalid URI: The hostname could not be parsed.

**Comment by BrianNowak** [comment]
line #48 and #54 are the same

**Comment by KelvinTegelaar** [comment]
Wow, seems like i missed that after a big rename. Will be fixed in next release.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

Bahialaan 600A
​3065 WC Rotterdam 
​+31 (0) 10 2121806
Kabelweg 21 
1014 BA Amsterdam 
+31 (0) 20 7602760
Kelvin Tegelaar
CTO
+31 6 41578650
limenetworks.nl
Heb je vragen over Lime Networks of over IT?
​Check: www.limenetworks.nl/faq
Ontdek hier meer
​​over Projecten en Migraties
Bekijk de brochure
