### ISSUE TITLE
Azurewebsite code

### ISSUE THREAD

**Issue by JvDrunen** [KelvinTegelaar/PowerShellWarrantyReports#65]
Hi @KelvinTegelaar 

would it be possible to share the code for the warrantyapiproxy in azure?

Thanks

**Comment by KelvinTegelaar** [comment]
Lol no

**Comment by aidan-casey** [comment]
@KelvinTegelaar - I am a little confused/concerned about your aversion here. Seems like open sourcing the API gateway would be an easy way to a) receive contributions and b) allow users to self-host the gateway with their own API keys instead of continue to run into situations where it has been shut down. 

Due to the unreliability of this implementation (see #44, #47, #63, #72) I've been tasked with building our own version. Since this isn't a very difficult project, we will expect to get that open sourced in the near future.

**Comment by KelvinTegelaar** [comment]
Good luck with that.

**Comment by aidan-casey** [comment]
Appreciate it. 🙂
